CREATE TABLE IF NOT EXISTS t_rate (
   ID        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   TYPE      CHAR(1) NOT NULL, -- U - USD, E - EURO
   DATE      INTEGER NOT NULL,
   RATE      REAL NOT NULL
);
